
services:
  audiobookshelf:
    labels:
      # watchtower
      com.centurylinklabs.watchtower.enable: true

      # traefik
      traefik.enable: true
      traefik.docker.network: traefik
      # https
      traefik.http.routers.audiobookshelf.rule: Host(`audiobook.${DOMAIN}`)
      traefik.http.routers.audiobookshelf.entrypoints: https
      traefik.http.routers.audiobookshelf.tls: true
      traefik.http.routers.audiobookshelf.tls.certResolver: cloudflare
      raefik.http.routers.audiobookshelf.tls.domains[0].main: audiobook.${DOMAIN}
      traefik.http.routers.audiobookshelf.service: audiobookshelf
      # service
      traefik.http.services.audiobookshelf.loadbalancer.server.port: 80
#     networks:
#       - traefik

# networks:
#   traefik:
#     external: true