version: "3.9"
services:
  tgmount:
    image: ghcr.io/energostalin/audiobook-tg:latest
    env_file: .env # uncomment to use
    build:
      context: .
      cache_from:
        - ghcr.io/energostalin/audiobook-tg:latest
      tags:
        - ghcr.io/energostalin/audiobook-tg:${RELEASE_VERSION-0}
        - ghcr.io/energostalin/audiobook-tg:latest
      x-bake:
        platforms:
          - linux/amd64
          - linux/arm64
    cap_add:
      - SYS_ADMIN
    devices:
      - /dev/fuse:/dev/fuse:rw
    security_opt:
      - apparmor:unconfined
    volumes:
      - type: volume
        source: book
        target: /audiobooks
        bind:
          propagation: rshared

      - ./config.yaml:/config.yaml
      - ./tgfs.session:/tgfs.session
    restart: unless-stopped

  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:edge
    cap_add:
      - SYS_ADMIN
    devices:
      - /dev/fuse:/dev/fuse:rw
    security_opt:
      - apparmor:unconfined
    volumes:
      - type: volume
        source: book
        target: /audiobooks
        bind:
          propagation: rshared

      - ./metadata:/metadata
      - ./config:/config
    ports:
      - 80:80
    depends_on:
      tgmount:
        condition: service_healthy
    restart: unless-stopped